import os

DXAPI_SSL_TERMINATION_ENV = "DXAPI_SSL_TERMINATION"
DXAPI_SSL_TRUST_ALL_ENV = "DXAPI_SSL_TRUST_ALL"


def env_true(name: str) -> bool:
    return os.environ.get(name, "").casefold() == "true"


def dxapi_ssl_termination_enabled() -> bool:
    return env_true(DXAPI_SSL_TERMINATION_ENV)


def dxapi_ssl_trust_all_enabled() -> bool:
    return env_true(DXAPI_SSL_TRUST_ALL_ENV)


class SettingsEnv:
    TIMEBASE_URL = "TIMEBASE_URL"
    TIMEBASE_USERNAME = "TIMEBASE_USERNAME"
    TIMEBASE_PASSWORD = "TIMEBASE_PASSWORD"
    TIMEBASE_OAUTH2_TOKEN_URL = "TIMEBASE_OAUTH2_TOKEN_URL"
    TIMEBASE_OAUTH2_CLIENT_ID = "TIMEBASE_OAUTH2_CLIENT_ID"
    TIMEBASE_OAUTH2_CLIENT_SECRET = "TIMEBASE_OAUTH2_CLIENT_SECRET"
    TIMEBASE_OAUTH2_SCOPE = "TIMEBASE_OAUTH2_SCOPE"
    TIMEBASE_OAUTH2_TOKEN_PARAMS = "TIMEBASE_OAUTH2_TOKEN_PARAMS"
    TIMEBASE_AUTH_MODE = "TIMEBASE_AUTH_MODE"
    TIMEBASE_HTTP_URL = "TIMEBASE_HTTP_URL"
    TIMEBASE_READ_ONLY = "TIMEBASE_READ_ONLY"
    TIMEBASE_SERVERS = "TIMEBASE_SERVERS"
    MCP_TRANSPORT = "MCP_TRANSPORT"
    MCP_HOST = "MCP_HOST"
    MCP_PORT = "MCP_PORT"
    MCP_LOG_LEVEL = "MCP_LOG_LEVEL"
    MCP_MAX_CONCURRENT_OPS = "MCP_MAX_CONCURRENT_OPS"
    MCP_MAX_IDLE_CLIENTS = "MCP_MAX_IDLE_CLIENTS"
    MCP_OPERATION_TIMEOUT_SECONDS = "MCP_OPERATION_TIMEOUT_SECONDS"
    MCP_AUTH_ISSUER_URL = "MCP_AUTH_ISSUER_URL"
    MCP_AUTH_JWKS_URL = "MCP_AUTH_JWKS_URL"
    MCP_AUTH_AUDIENCE = "MCP_AUTH_AUDIENCE"
    MCP_AUTH_REQUIRED_SCOPES = "MCP_AUTH_REQUIRED_SCOPES"
    MCP_AUTH_PUBLIC_URL = "MCP_AUTH_PUBLIC_URL"
    MCP_AUTH_API_KEYS_FILE = "MCP_AUTH_API_KEYS_FILE"
